import AdminLayout from "@/components/layouts/admin_layout";
import { ThemeProvider } from "@/components/theme_provider";
import { Metadata } from "next";
import type React from "react"

export const metadata: Metadata = {
  title: "CritalPoint Management Admin",
  description: "Generated by create next app with Archivo font",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <ThemeProvider>
    <AdminLayout>{children}</AdminLayout>
    </ThemeProvider>
  )
}
