import DashboardLayout from "@/components/layouts/dashboard_layout";
import { ThemeProvider } from "@/components/theme_provider";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "CritalPoint Management User",
  description: "Generated by create next app with Archivo font",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className={``}
      >
           <ThemeProvider>
        <DashboardLayout>{children}</DashboardLayout>
          </ThemeProvider>
      </div>
  );
}
