import DashboardLayout from "@/components/layouts/dashboard_layout";
import { ThemeProvider } from "@/components/theme_provider";
import type { Metadata } from "next";
import { Archivo } from "next/font/google";

const archivoSans = Archivo({
  variable: "--font-archivo-sans",
  subsets: ["latin"],
});

const archivoMono = Archivo({
  variable: "--font-archivo-mono",
  subsets: ["latin"],
  weight: ["400", "700"], // Optional weight specification
});

export const metadata: Metadata = {
  title: "CrytalPoint Management Dashboard",
  description: "Generated by create next app with Archivo font",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className={`${archivoSans.variable} ${archivoMono.variable} antialiased`}
      >
           <ThemeProvider>
        <DashboardLayout>{children}</DashboardLayout>
          </ThemeProvider>
      </div>
  );
}
